spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meedesk_meeting?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: pts123456.
          #最大活跃数
    maxActive: 20
      #初始化数量
    initialSize: 1
      #最大连接等待超时时间
    maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall

  cache:
    ehcache:
      config: classpath:/config/ehcache.xml

  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
    charset: UTF-8
    cache: true
    request-context-attribute: request
    content-type: text/html
    allow-request-override: false
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefix:

  jooq:
    sql-dialect: org.hibernate.dialect.SQLServerDialect

  servlet:
    multipart:
      enabled: false
  resources:
    static-locations: classpath:/static/,file:${ftp.path}
  profiles:
    active: empower
server:
  port: 8088
  servlet:
    context-path: /meetingServer
    session:
      timeout: 3600s
  http:
    encoding:
      charset: utf-8
      enabled: true
  tomcat:
    max-http-post-size: -1
#mybatis
mybatis-plus:
    mapper-locations: classpath:mappers/*.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.meeting.entity
    global-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 2
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      db-column-underline: false
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      #序列接口实现类配置
      #key-generator: com.baomidou.springboot.xxx
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 0
      logic-not-delete-value: 1
      #自定义SQL注入器
      #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
ftp:
  path: /Users/yiwen/ftp
meeting:
  type: lan
socketio:
  host: 0.0.0.0
  port: 15741
  #设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  #协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 5000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 2000

serial:
  up: FF101100DD
  down: FF101100EE
  pause: FF101100CC


